version: 0.2

env:
  parameter-store:
    SIGNER_PROFILE_ARN: 'signer-profile-arn'

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_REPO_URI
      - echo Downloading AWS Signer and Notation CLI
      - wget https://d2hvyiie56hcat.cloudfront.net/linux/amd64/installer/deb/latest/aws-signer-notation-cli_amd64.deb
      - echo Installing AWS Signer and Notation CLI
      - sudo dpkg -i -E aws-signer-notation-cli_amd64.deb
      - notation version
  build:
    commands:
      - cd ./my-app
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker BreakTheBuild
      - docker tag myapp:$IMAGE_TAG $IMAGE_REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"my-app","imageUri":"%s"}]' $IMAGE_REPO_URI:$IMAGE_TAG > $CODEBUILD_SRC_DIR/imagedefinitions.json

artifacts:
    files: imagedefinitions.json